//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRefiner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool initCollapsed {
            get {
                return ((bool)(this["initCollapsed"]));
            }
            set {
                this["initCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool onlyPPC {
            get {
                return ((bool)(this["onlyPPC"]));
            }
            set {
                this["onlyPPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool betterSQL {
            get {
                return ((bool)(this["betterSQL"]));
            }
            set {
                this["betterSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoDark {
            get {
                return ((bool)(this["autoDark"]));
            }
            set {
                this["autoDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"TypeName\":\"AppRefiner.Stylers.AmbiguousClassReferenceStyler\",\"Active\":true},{\"" +
            "TypeName\":\"AppRefiner.Stylers.ClassNameMismatch\",\"Active\":true},{\"TypeName\":\"App" +
            "Refiner.Stylers.DeadCodeStyler\",\"Active\":true},{\"TypeName\":\"AppRefiner.Stylers.F" +
            "indFunctionParameterStyler\",\"Active\":true},{\"TypeName\":\"AppRefiner.Stylers.Inval" +
            "idAppClass\",\"Active\":true},{\"TypeName\":\"AppRefiner.Stylers.LinterSuppressionStyl" +
            "er\",\"Active\":false},{\"TypeName\":\"AppRefiner.Stylers.MeaninglessVariableNameStyle" +
            "r\",\"Active\":false},{\"TypeName\":\"AppRefiner.Stylers.MissingConstructor\",\"Active\":" +
            "false},{\"TypeName\":\"AppRefiner.Stylers.MissingMethodImplementation\",\"Active\":tru" +
            "e},{\"TypeName\":\"AppRefiner.Stylers.MissingSemicolon\",\"Active\":false},{\"TypeName\"" +
            ":\"AppRefiner.Stylers.PropertyAsVariable\",\"Active\":false},{\"TypeName\":\"AppRefiner" +
            ".Stylers.RedeclaredVariables\",\"Active\":true},{\"TypeName\":\"AppRefiner.Stylers.Reu" +
            "sedForIterator\",\"Active\":true},{\"TypeName\":\"AppRefiner.Stylers.SQLVariableCountS" +
            "tyler\",\"Active\":true},{\"TypeName\":\"AppRefiner.Stylers.SyntaxErrors\",\"Active\":tru" +
            "e},{\"TypeName\":\"AppRefiner.Stylers.TodoFixmeStyler\",\"Active\":false},{\"TypeName\":" +
            "\"AppRefiner.Stylers.TypeErrorStyler\",\"Active\":true},{\"TypeName\":\"AppRefiner.Styl" +
            "ers.UndefinedVariables\",\"Active\":false},{\"TypeName\":\"AppRefiner.Stylers.Unimplem" +
            "entedAbstractMembersStyler\",\"Active\":false},{\"TypeName\":\"AppRefiner.Stylers.Unim" +
            "portedClassStyler\",\"Active\":true},{\"TypeName\":\"AppRefiner.Stylers.UnusedImports\"" +
            ",\"Active\":true},{\"TypeName\":\"AppRefiner.Stylers.UnusedVariables\",\"Active\":true}," +
            "{\"TypeName\":\"AppRefiner.Stylers.WrongExceptionVariableStyler\",\"Active\":false}]")]
        public string StylerStates {
            get {
                return ((string)(this["StylerStates"]));
            }
            set {
                this["StylerStates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""TypeName"":""AppRefiner.Linters.CreateSQLVariableCount"",""Active"":true},{""TypeName"":""AppRefiner.Linters.EmptyCatchBlockLinter"",""Active"":false},{""TypeName"":""AppRefiner.Linters.FlowerBoxHeader"",""Active"":false},{""TypeName"":""AppRefiner.Linters.FunctionParameterCountLinter"",""Active"":false},{""TypeName"":""AppRefiner.Linters.GetHTMLTextVariableCount"",""Active"":true},{""TypeName"":""AppRefiner.Linters.LinterSuppressionProcessor"",""Active"":true},{""TypeName"":""AppRefiner.Linters.LongExpressionLinter"",""Active"":false},{""TypeName"":""AppRefiner.Linters.MultiLineRemCommentLinter"",""Active"":true},{""TypeName"":""AppRefiner.Linters.NestedIfElseCheck"",""Active"":false},{""TypeName"":""AppRefiner.Linters.RecursiveFunctionLinter"",""Active"":false},{""TypeName"":""AppRefiner.Linters.ReusedForIterator"",""Active"":true},{""TypeName"":""AppRefiner.Linters.SQLExecVariableCount"",""Active"":true},{""TypeName"":""AppRefiner.Linters.SQLLongString"",""Active"":false},{""TypeName"":""AppRefiner.Linters.SQLWildCard"",""Active"":true},{""TypeName"":""AppRefiner.Linters.TodoFixmeLinter"",""Active"":false},{""TypeName"":""AppRefiner.Linters.UseOfObjectType"",""Active"":true}]")]
        public string LinterStates {
            get {
                return ((string)(this["LinterStates"]));
            }
            set {
                this["LinterStates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LintingReports")]
        public string LintReportPath {
            get {
                return ((string)(this["LintReportPath"]));
            }
            set {
                this["LintReportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plugins")]
        public string PluginDirectory {
            get {
                return ((string)(this["PluginDirectory"]));
            }
            set {
                this["PluginDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoIndent {
            get {
                return ((bool)(this["autoIndent"]));
            }
            set {
                this["autoIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoPair {
            get {
                return ((bool)(this["autoPair"]));
            }
            set {
                this["autoPair"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool vimModeEnabled {
            get {
                return ((bool)(this["vimModeEnabled"]));
            }
            set {
                this["vimModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SnapshotDatabasePath {
            get {
                return ((string)(this["SnapshotDatabasePath"]));
            }
            set {
                this["SnapshotDatabasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""TypeName"":""AppRefiner.TooltipProviders.ActiveIndicatorsTooltipProvider"",""Active"":true},{""TypeName"":""AppRefiner.TooltipProviders.ScopeTooltipProvider"",""Active"":true},{""TypeName"":""AppRefiner.TooltipProviders.PeopleSoftObjectTooltipProvider"",""Active"":true},{""TypeName"":""AppRefiner.TooltipProviders.MethodParametersTooltipProvider"",""Active"":true},{""TypeName"":""AppRefiner.TooltipProviders.VariableInfoTooltipProvider"",""Active"":false},{""TypeName"":""AppRefiner.TooltipProviders.InferredTypeTooltipProvider"",""Active"":true},{""TypeName"":""AppRefiner.TooltipProviders.AppClassTooltipProvider"",""Active"":true}]")]
        public string TooltipStates {
            get {
                return ((string)(this["TooltipStates"]));
            }
            set {
                this["TooltipStates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"TypeName\":\"AppRefiner.LanguageExtensions.BuiltIn.ArrayExtensions\",\"Active\":tru" +
            "e},{\"TypeName\":\"AppRefiner.LanguageExtensions.BuiltIn.StringExtensions\",\"Active\"" +
            ":true}]")]
        public string LanguageExtensionStates {
            get {
                return ((string)(this["LanguageExtensionStates"]));
            }
            set {
                this["LanguageExtensionStates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{}")]
        public string LanguageExtensionConfigs {
            get {
                return ((string)(this["LanguageExtensionConfigs"]));
            }
            set {
                this["LanguageExtensionConfigs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool promptForDB {
            get {
                return ((bool)(this["promptForDB"]));
            }
            set {
                this["promptForDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbConnectionSettings {
            get {
                return ((string)(this["DbConnectionSettings"]));
            }
            set {
                this["DbConnectionSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxFileSnapshots {
            get {
                return ((int)(this["MaxFileSnapshots"]));
            }
            set {
                this["MaxFileSnapshots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TNS_ADMIN {
            get {
                return ((string)(this["TNS_ADMIN"]));
            }
            set {
                this["TNS_ADMIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkEventMapping {
            get {
                return ((bool)(this["checkEventMapping"]));
            }
            set {
                this["checkEventMapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkEventMapXrefs {
            get {
                return ((bool)(this["checkEventMapXrefs"]));
            }
            set {
                this["checkEventMapXrefs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showClassText {
            get {
                return ((bool)(this["showClassText"]));
            }
            set {
                this["showClassText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showClassPath {
            get {
                return ((bool)(this["showClassPath"]));
            }
            set {
                this["showClassPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool codeFolding {
            get {
                return ((bool)(this["codeFolding"]));
            }
            set {
                this["codeFolding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool rememberFolds {
            get {
                return ((bool)(this["rememberFolds"]));
            }
            set {
                this["rememberFolds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool overrideFindReplace {
            get {
                return ((bool)(this["overrideFindReplace"]));
            }
            set {
                this["overrideFindReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool overrideOpen {
            get {
                return ((bool)(this["overrideOpen"]));
            }
            set {
                this["overrideOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smartOpenConfig {
            get {
                return ((string)(this["smartOpenConfig"]));
            }
            set {
                this["smartOpenConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FunctionCacheDatabasePath {
            get {
                return ((string)(this["FunctionCacheDatabasePath"]));
            }
            set {
                this["FunctionCacheDatabasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCenterDialogs {
            get {
                return ((bool)(this["AutoCenterDialogs"]));
            }
            set {
                this["AutoCenterDialogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoMaximizeEditorWindows {
            get {
                return ((bool)(this["AutoMaximizeEditorWindows"]));
            }
            set {
                this["AutoMaximizeEditorWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool multiSelection {
            get {
                return ((bool)(this["multiSelection"]));
            }
            set {
                this["multiSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool lineSelectionFix {
            get {
                return ((bool)(this["lineSelectionFix"]));
            }
            set {
                this["lineSelectionFix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"variableSuggestions\":true,\"functionSignatures\":true,\"objectMembers\":true,\"syste" +
            "mVariables\":true}")]
        public string autoSuggestSettings {
            get {
                return ((string)(this["autoSuggestSettings"]));
            }
            set {
                this["autoSuggestSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alphabet")]
        public string theme {
            get {
                return ((string)(this["theme"]));
            }
            set {
                this["theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool theme_filled {
            get {
                return ((bool)(this["theme_filled"]));
            }
            set {
                this["theme_filled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsUpgraded {
            get {
                return ((bool)(this["SettingsUpgraded"]));
            }
            set {
                this["SettingsUpgraded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWhatsNewDialog {
            get {
                return ((bool)(this["ShowWhatsNewDialog"]));
            }
            set {
                this["ShowWhatsNewDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSeenVersion {
            get {
                return ((string)(this["LastSeenVersion"]));
            }
            set {
                this["LastSeenVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool miniMapOpen {
            get {
                return ((bool)(this["miniMapOpen"]));
            }
            set {
                this["miniMapOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showParamNames {
            get {
                return ((bool)(this["showParamNames"]));
            }
            set {
                this["showParamNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useEnhancedEditor {
            get {
                return ((bool)(this["useEnhancedEditor"]));
            }
            set {
                this["useEnhancedEditor"] = value;
            }
        }
    }
}
